### ISSUE TITLE
As a user, I should only see large images of annotated pages, overview images, and insertions because the material is still under copyright.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#111]
## Notes for testing
One way to test that images are restricted properly is to either add or remove interventions and check that the display matches.  You may need to check with a different browser or use a force reload, because the browser will cache the images.

This is kind of a reverse user story, but documenting this because it's important that we protect the urls and image content since the materials are under copyright and we don't want unnecessary exposure.

**Comment by rlskoeser** [comment]
@kac3 as a follow up to the email conversation about references and corresponding interventions and canvases - current logic is to display any overview image (based on labels from Plum), any insertion page (based on labels from Plum), and any other page with an intervention associated in the database.  We could restrict further if you think we need to (only pages with interventions that correspond to references?), but I think that will require a lot more data work from the team before we have content to show and I'm not sure what it gets us.  Will we be showing too large a percentage of the books if we show all pages with documented interventions?

**Comment by kac3** [comment]
@rlskoeser I think what you describe is the way to go -- and much less labor-intensive for us.  It just means that, in order to avoid showing too large a percentage of the book, we need to make sure to limit ourselves only to pages with references (which is what we're doing in theory anyway) as we enter intervention data.  Also, that means any interventions from flyleaves will also be pulled in.

It is now occurring to me now that the associated canvas feature should perhaps be used *only* to indicate that the page includes a quotation that shows up in a Derrida work. If I'm not mistaken, @xinyil has been working on a bookmark-style label that indicates this for a given page.

**Comment by xinyil** [comment]
@kac3 Please see the bookmark and some other updates/questions regarding visual elements in an email I sent last week. It might got overlooked in the thread, I just forwarded to you again in case.

**Comment by kac3** [comment]
@xinyil Apologies for the delay - I sent you an email with feedback on the visual elements.
