### ISSUE TITLE
citations: associate with interventions/annotations

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#14]
As a record editor, I want to be able to associate a citation with one or more interventions (annotations or insertions) so that I can identify instances where citations relate in an explicit way to interventions (for example, a passage is quoted in the Derrida text and underlined in the book from the library).

As a record editor, when editing this field in the Django admin, I want it to automatically filter to only those intervetions associated with the digital edition of the book (i.e. if a reference is set to BookA, only interventions associated with BookA show up).

- [x]  revise help text to make it clear interventions are restricted to associated digitized volume
- [x] disable intervention select if no digitized volume is associated

**Comment by rlskoeser** [comment]
Needs to support associating citation with more than one intervention.

UI/approach TBD.  Does this make more sense to add to the annotation editor UI or does it belong on the citation editor in the Django admin interface?  Will editors start from the annotation or start from the citation?

**Comment by rlskoeser** [comment]
My inclination is to put this in the django admin interface for editing references because I think the UI work will be easier.  We'll eventually have enough intervention data that this needs an autocomplete for performance reasons; we'll need to make sure that the brief listing of an intervention is meaningful enough to allow selection from the admin interface.

**Comment by kac3** [comment]
@bwhicks @rlskoeser Please see comment on #16.
