### ISSUE TITLE
Banner image resizing 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#160]
After dropping a full image to test the banner, I found out some unexpected behavior. Please see following descriptions for the right behavior.

When resizing the window:
- the height of the banner area and banner image shouldn't change
- image should be centered, and constrained according to the height, and will be cut-off from both sides
- there shouldn't any extra spacing added around the image

**Comment by xinyil** [comment]
- the height of the banner at L viewport should be 600px fixed
- images should be centered, and constrained according to the height, and will be CUT-OFF from both sides (seeing form a 1440*900px screen won't see the whole image)

**Comment by xinyil** [comment]
I'm waiting for this one to be fixed, so I can test images on live site and revise.

**Comment by kevinglover** [comment]
@xinyil The Apple Education site is using different cropped images at different viewport sizes to achieve the positioning of the image in the banner. In order to replicate this, we would need to have the final banner images set and cropped.

https://images.apple.com/v/education/education/i/images/overview/hero_alt_large.jpg
https://images.apple.com/v/education/education/i/images/overview/hero_alt_medium.jpg
https://www.apple.com/v/education/education/i/images/overview/hero_alt_small.jpg

**Comment by xinyil** [comment]
@kevinglover Thank you for the reply. I didn't mean to bother you - Rebecca is cleaning up the project and I'm taking another pass on the issues.

Yes. we'll have 3 images for the different sizes. In fact, we had 3 placeholder images.

**Comment by rlskoeser** [comment]
@xinyil I just updated the test site with some small changes, please take a look.  The banner image was already centered and set to full height and auto-width, I think it was just the size of the container that was missing.

**Comment by xinyil** [comment]
@rlskoeser Thanks. It looks right at three sizes. I'm holding off on closing this till we replaced the place holder image with the actual ones.

**Comment by rlskoeser** [comment]
@xinyil test site has been updated with your latest banner images.
