### ISSUE TITLE
data migration to reassociate collection references with book section by chapter

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#164]
## Notes for testing
- data migration has been run on the test site, which was updated with a copy of production data from 3/7/2018
- references with page numbers that match an existing book section should be moved to the book section instead of the book
- please review the books and a handful of the book sections listed below (no need to check all)
- You may also find it useful to check the public display of references on the site to see how they are listed and displayed
- These are the books and book sections that were detected by the script as potentially needing updates:
  - Essais linguistiques
    - La stratification du langage
    - Langue et parole
  - L'Ecriture et la psychologie des peuples: actes de colloque
    - L'Asie Mineure. Les Hittites, peuple à double écriture
    - L'écriture cunéiforme et la civilisation mésopotamienne
    - L'écriture et le droit
    - La Chine. Aspects et fonctions de l'écriture
    - La civilisation égéenne. Les écritures crétoises et mycéniennes
    - Les Primitifs. Signaux et symboles
    - Les Sémites et l'alphabet. Écritures concrètes et écritures abstraites
    - Les hiéroglyphes. L'évolution des écritures égyptiennes
    - Les écritures indiennes. Le monde indien et son système graphique.
  - Émile ou de l'éducation
   - Profession de foi du vicaire Savoyard
  - Œuvres choisies
  - Scienza Nuova

## Notes for development
Needed to correctly handle references to the multi-author work  _L’écriture et la psychologie des peoples_ so that references are associated with the correct author in filters and data visualizations.

**Comment by kac3** [comment]
@rlskoeser This seems to be working really well.  During testing I ran into a couple glitches, most of which are not necessarily directly related to this issue, but which I'll go ahead and mention here:

1. While some book section references do display thumbnails, some do not.  For the book section James Février, "Les Sémites et l'alphabet" (from _L'écriture et la psychologie des peuples_), for example, there are no thumbnail images displayed with the references, even when the pages referenced are annotated and show up in the image gallery on the book page.  (And we should at least get the book cover as a thumbnail when there is not annotated page image, yes?)

![screen shot 2018-03-25 at 8 38 19 pm](https://user-images.githubusercontent.com/26174024/37882145-b362e92c-306e-11e8-9418-727f2f4e697d.png)

![screen shot 2018-03-25 at 8 51 44 pm](https://user-images.githubusercontent.com/26174024/37882151-b8fe3f8a-306e-11e8-90eb-ceff7b6da77b.png)

I'm noticing that on the admin side this book section does is not listed as "is digitized," and I'm wondering if that's part of the issue.  But it's strange -- shouldn't a book section automatically be recognized as digitized when its "Collected in" instance is digitized? 

- The same issue exists with Vico, "Scienza Nuova" (cover should at least show here).

![screen shot 2018-03-25 at 9 00 21 pm](https://user-images.githubusercontent.com/26174024/37882292-14344ee8-3070-11e8-96cc-30311ab5b199.png)

- But this doesn't necessarily seem to be a section-specific issue.  There is no thumbnail for references to _L'écriture et la différence_, for example.
 
![screen shot 2018-03-25 at 9 10 07 pm](https://user-images.githubusercontent.com/26174024/37882386-ec8478cc-3070-11e8-80e3-f9f71b1582b4.png)


2. Another thumbnail issue: when there is a thumbnail image of a page, clicking on it takes you to the book page, not the specific page image.  Is that how this should work?

![screen shot 2018-03-25 at 9 11 22 pm](https://user-images.githubusercontent.com/26174024/37882423-396a887a-3071-11e8-8625-97fa6d5950ea.png)

3. When searching for references in the search bar at the top of the page, book sections don't show up in the results unless the author/title is in the anchor text of the reference.  For example, if I search for "Février," I don't get the references that cite this section just by page number (such as the one on p. 20 above).  

4. The presence of accents in names seems to mess up alphabetization when sorting by "Author of Cited Work" in the Reference List (not sure if it does elsewhere, as well).  Instead of coming where they should in alphabetical order, authors with accents in the second letter of their last name get bumped to the end of that letter. For example, James Février shows up at the end of the "F" authors, after Freud. The same thing happens Claude Lévi-Strauss and Henri Lévy-Bruhl in the "L" authors.

![screen shot 2018-03-25 at 9 14 31 pm](https://user-images.githubusercontent.com/26174024/37882526-05c1d018-3072-11e8-9ec6-9308a27da7d3.png)

Otherwise, the sections seem to be working well now!

**Comment by kac3** [comment]
@rlskoeser Updating to add that the reference search in general seems to be acting wonky.  I just did a search for "Nietzsche" and came up only with results that have Nietzsche in the reference anchor text, but not the epigraph citing Nietzsche, _La Naissance de la tragédie_, on DG p. 15.  (I know this is a different issue, but unsure where to put it!)

**Comment by rlskoeser** [comment]
@kac3 thank you for flagging these important issues!  I have noticed some of them in passing, but haven't had time to investigate.  I created a new issue - #175 - where we can all make notes of things like this as we find them, and I've added your two comments here to that issue.  If you're comfortable that the reference data migration is working as expected, please go ahead and close this issue.
