### ISSUE TITLE
Filters - default to Cited by Derrida in DG

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#167]
- Cited by Derrida in DG should be selected and disabled by defualt, in both library page, and reference list page, if we're not doing chapters.
- currently on reference list page, "Cited by Derrida in DG" in selected by defualt, but when any other filter is selected, this will become unselected. and it can't be selected mannualy because it's disablesd 

<img width="527" alt="screen shot 2018-03-07 at 5 08 54 pm" src="https://user-images.githubusercontent.com/17734456/37121132-424c34ac-222a-11e8-968b-97746374b09b.png">

<img width="301" alt="screen shot 2018-03-07 at 5 10 31 pm" src="https://user-images.githubusercontent.com/17734456/37121227-8abad950-222a-11e8-9311-c3f49fad2fbf.png">

**Comment by rlskoeser** [comment]
@kac3 I had a possible aha moment about this, wanted to check with you: according to Xinyi's design, the library page should be restricted only to books that are cited in _DG_ - I had that turned off because it was causing problems, it seemed to be restricting the list too much.  My possible aha - do we want to restrict to _instances_ that are cited, or do we want to show all copies of a work that is cited?

**Comment by kac3** [comment]
@rlskoeser We definitely want to show all instances, not just cited instances. 

My preference for the library page, in other words, would be to show all cited instances -- i.e., all instances that have a reference associated with them -- AND all other instances of the same work.

We should also display any extant instances of the Derrida work itself (in this case DG).

In principle that should include *everything* we have in the system at this point.

**Comment by rlskoeser** [comment]
@kac3 I did some querying on production to get some counts to help us figure this out.  The numbers in production look much better than the data I have, so I can tell that the team has been hard at work!  

- 159 work instances that are *books* (excludes journal articles and book sections)
- 71 of those are extant
- 67 of those are cited directly (I'm using the `cited_in` property in the database to check this)
- when I expand my filter to include any instances of a work that is cited, the count goes up to 70; the one that is not included is _Essai sur l'origine des langues_ (1817)

When I switch to querying based on related references in the database, I only get 59 extant instances that have references directly associated and 61 for instances where any copy of the work is cited.  I'll stick to that `is_cited` flag.

I also did a preliminary check on digital editions matching up with instances.
- 54 extant books are currently associated with digital editions; there is one journal instance, _Les anagrammes de Ferdinand de Saussure_ (1964) that is associated with a digital edition, looks like a mis-association to me
- 12 manifests (digital editions) in production are currently not associated with an instance; I'll re-run the digital edition import script and report on which ones aren't automatically matching

**Comment by rlskoeser** [comment]
Forgot to say in my last comment: I don't think  _DG_ is currently included as a library work / instance, so it won't be displayed on the library browse page.  But you could add records to document the copies that he owned.

**Comment by rlskoeser** [comment]
@kac3 here are the decisions I think we need from you: 
- what filters do you want included by default on the library browse? it is currently restricted to extant books
- do you want the "cited in" filter pre-populated to _DG_? currently the design calls for cited in preset to _DG_ and disabled (i.e., you can't turn off that filter), but I think doing that loses some content we should display
- please confirm: the "cited in" filter should select all copies of a work that has any instance cited (I think this will make it harder to identify actual cited copies)

**Comment by rlskoeser** [comment]
Correction: I see now that Xinyi's latest design has the extant filter turned on by default, but it is something people can turn off.  That seems valuable - I'll update the site so you can see that.

**Comment by kac3** [comment]
@rlskoeser 

- Having the extant filter turned on by default but able to be turned off (as it currently is on the test site) is perfect.
- I see what you mean about losing content by having the "cited in" filter preset to DG and disabled.  Let's not have it be preset, then.
- You're totally right that this (i.e., having "cited in" filter select all copies of a work that has any instance cited) makes it harder to identify the actual cited copies.  As long as we don't have the "cited in" pre-selected -- so that the non-cited instances are visible by default on the Library page -- I think we should revert to having **only** cited instances appear when "cited in DG" is selected.  I was just worried about other editions/translations getting buried if they didn't show up on the Library page, but this seems like a very good solution.

**Comment by rlskoeser** [comment]
@kac3 please provide updated help text for the library page, as it's no longer accurate with these changes.  Current text:
> Only books extant in the Library of Jacques Derrida collection, held at the Princeton University Library’s Department of Rare Books and Special Collections, are displayed below.

**Comment by kac3** [comment]
@rlskoeser I think we can just eliminate this text and leave what's above ("Browse Derrida's copies..."). Does that make sense?

**Comment by rlskoeser** [comment]
@kac3 ah, I see how it's kind of redundant now...  It still seems nice to mention PUL/RBSC, though; does it make sense to mention digitized editions are from RBSC?

**Comment by kac3** [comment]
@rlskoeser What if we make sure to mention PUL/RBSC on the home page (as in current version of text) but not mention it here?  I say this partly because the Library page text has always seemed a bit cluttered to me and I'm relishing the possibility of being able to unclutter it a bit.  (I'm also open to including something, though, if we can come up with the wording.)

**Comment by rlskoeser** [comment]
@kac3 either way sounds fine to me; @xinyil any design implications?

**Comment by kac3** [comment]
@xinyil @rlskoeser Another little wording issue -- not filters, but search results:

![screen shot 2018-04-02 at 4 48 32 pm](https://user-images.githubusercontent.com/26174024/38215419-ccff62d4-3695-11e8-852d-39c72f40f01c.png)

"Annotations" should now read "Interventions," yes?

**Comment by xinyil** [comment]
removing this sentence sounds good to me. mentioning PUL/RBSC on the home page and credit page would be enough.

it reminds me that we have a related help text in the image gallery, which doesn't seem to be implemented yet?
<img width="713" alt="screen shot 2018-04-02 at 4 49 34 pm" src="https://user-images.githubusercontent.com/17734456/38215469-fa85fcd6-3695-11e8-9c83-cf24fec03b69.png">

**Comment by rlskoeser** [comment]
@xinyil @kac3 I think this one is resolved now.  Can one of you review and close or let me know what else needs to be done?

@xinyil I added the sentence on the gallery page.

@kac3 I corrected the search result heading.

**Comment by xinyil** [comment]
since library page is displaying more books that are not been cited, it makes sense to leave it "Cited by " off on library page, but have it on by default on reference page. It's behaving as expected now.


@rlskoeser this issue has not been fixed:
- currently on reference list page, "Cited by Derrida in DG" in selected by default, but when any other filter is selected, this will become unselected. and it can't be selected manually because it's disabled

**Comment by rlskoeser** [comment]
@xinyil I had a flaw in the logic for loading form defaults that was affecting other things.  I finally fixed it (after a few tries).  That fix should resolve the `Cited in...` filter display on the reference list.  (The logic doesn't change because all our references are currently cited in _DG_, but now the display will be clear and match the logic.) 

I thought @kac3 was saying to leave the library 'cited in' filter default to on - but maybe I mixed up the library and reference list pages?  Let me know, it's easy to change the default.

**Comment by kac3** [comment]
@rlskoeser @xinyil I would like to have the "cited in" filter default to **off** on the Library page (so that the Library shows all extant copies/editions as default, with users able to see only editions cited in DG by selecting "cited in _DG_ themselves), but this filter should be **on** on the References List page (since all references are necessarily cited in _DG_).  Hoping that makes sense!

**Comment by rlskoeser** [comment]
@kac3 got it! Thank you for clarifying and thanks @xinyil for catching this.
