### ISSUE TITLE
people: add/edit person

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#17]
As a record editor, I want to add a new or edit an existing person so that I can document people associated with the Derrida Library.

**Comment by bwhicks** [comment]
Some fields I would expect might be likely things you would want for this: VIAF uri, their authorized name per viaf, birth, and death.

Possibly also: sort name (if you want to adjust sort order)

Able to associate: roles and relationships

I suspect the finalized schema from will clarify this.

**Comment by kac3** [comment]
Yes, we do want to be able to associate: roles and relationships. Thanks for catching that.

I will defer to Jean on the other questions.

**Comment by kac3** [comment]
@bwhicks Two things came up here:

1. We could probably ditch the "Family Group" field, since that won't really apply to the Derrida library.

2. I notice that under "Associated Books," the Books a person is a Creator (Author, Editor, etc.) of don't show up.  I think I understand why that's the case (because these are not relationships entered under person/book interaction), but it would be great if we could change this.  As is, when I go, for example, to Heidegger, I don't see any Associated Books.

There's another issue with Associated Books.  Under Person/Book Interaction I made Derrida the "Annotator" of "Being and Time."  But when I look at "Associated Books" for the Derrida person record, I only see this: 
![screen shot 2017-03-28 at 6 34 40 pm](https://cloud.githubusercontent.com/assets/26174024/24430601/5502f3b4-13e5-11e7-8f09-4e334fc37a19.png)

**Comment by bwhicks** [comment]
On this one, I'll gladly pull the family group field. It's just a matter of deleting it.

The associated books setup is probably a bit misleading for the context of this project. In Winthrop (for example) it represented a relationship like ownership of a book, etc. that didn't include annotator, creator, etc., since it was looking at a family library. I'll take some time to think about how to make this a useful inline for your purposes now that I see how you'd be using it.

**Comment by bwhicks** [comment]
@kac3 A change I have just made. We can talk today about how best to integrate author, editor, etc. Thanks for all the testing and feedback. It makes my job work!

<img width="1415" alt="screen shot 2017-03-29 at 9 47 46 am" src="https://cloud.githubusercontent.com/assets/17815297/24457634/d07d952e-1464-11e7-94a7-be97696a448a.png">
