### ISSUE TITLE
book sections associated with a digitized work should be considered digitized in admin

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#181]
I've updated the logic so book sections associated with a digitized work will now show as digitized in the admin; there was also a fix related to this logic that corrects the reference thumbnails for book sections

**Comment by kac3** [comment]
@rlskoeser Looks good! 

There is a similar issue with "is extant"  -- ideally this would automatically be selected for book section if book is extant.  As of now, we have some book sections that are marked digitized but not extant.  But  this seems low priority to me since we can enter it manually (which wasn't possible for "is digitized").

**Comment by rlskoeser** [comment]
@kac3 thanks for flagging that! I knew the book sections would be tricky.  FWIW, I have updated the Solr indexing logic so that book sections are considered extant if they belong to a book that is extant.  I don't think there's an easy for us to automatically set the `is_extant` field for you in the database, so would recommend you all set it there if you care about it - but I would say that's pretty low priority.

**Comment by rlskoeser** [comment]
@kac3 let me know if there's anything else urgent you need here - I think you need to live with a non-automatic extant field for book sections for now at least, but that it shouldn't have a very big impact.

**Comment by kac3** [comment]
@rlskoeser Nothing else urgent - and we can definitely live with entering the extant field manually for book sections. Going ahead and closing this one out!
