### ISSUE TITLE
people: associate roles and relationships with people

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#20]
As a record editor, I want to be able to associate roles and relationships to people so that I can document how they interacted with each other and the Derrida Library.

**Comment by kac3** [comment]
@bwhicks Once I've created a relationship, it doesn't seem that I can revert to having no relationship because it becomes a "required field."  For instance, I created a relationship between Pierre Aubenque and Jacques Derrida (relationship type "annotator"), and tried to undo it but was unable to unless I provided a new person or relationship type.

**Comment by bwhicks** [comment]
Hi @kac3. This one is I think an area where Grappelli (the admin interface we use with django), for all its virtues falls down a bit. You need to click the relationship (in this case, a from one I saw you had set) and then click the 'X' on the tabular inline. Then hit delete at the lower left. I can show you today or screenshot it.
