### ISSUE TITLE
interventions: associate with person and default to Derrida

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#37]
As an interventions data editor, I want to associate an intervention with the person who wrote it so that I can document the author when that information is known; I want “Derrida, Jacques” to be the default intervention author, and I want to be able to add or edit this information.

**Comment by rlskoeser** [comment]
I think in the foreign key for intervention author should have a callable set as the default value.  The callable will look up Derrida and return person or null.  Needs to be a callable since Derrida might not be in the database.

This covers django admin, but doesn't handle setting a default in the annotator interface.  We might need to extend the default canvas detail view so we can pass in custom context data (it seems like a poor idea to have the name hardcoded in more than one place).  I thought about doing that for the list of languages but worked around it.   If we don't want to go that route, maybe we could provide an annotation default via json view.

**Comment by bwhicks** [comment]
This is working and unit-tested, though I did not yet hook up an autocomplete for annotators (not sure what criteria we might be using to sort people usefully).
