### ISSUE TITLE
interventions: document language of anchor text

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#38]
As an interventions data editor, I want to document the language of anchor text and annotation text so that I can track use of languages across interventions.

- [x] add language foreign key fields
- [x] update intervention extra data & info to include language fields
- [x] language list via json for inclusion in annotator editor
- [x] update annotator init & plugin to add language fields
- [x] update plugin to display languages on marginalia item card

**Comment by rlskoeser** [comment]
Note that we only need to support a single language for each of these.

**Comment by kac3** [comment]
Hi @bwhicks @rlskoeser, I see where I can document the language of the anchor text -- but not where I can document the anchor text itself!  If that's because I neglected to create a user story, my apologies. We need a field for anchor text (in the image below, "guerres civiles") distinct from annotation text.

![screen shot 2017-07-18 at 11 57 41 am](https://user-images.githubusercontent.com/26174024/28312965-5500436c-6bb5-11e7-86e7-bb429e7b76c8.png)

**Comment by rlskoeser** [comment]
Whoops!  I thought about that in passing at some point (I wondered why we were only documenting the language of the anchor text) but failed to ask.  Let's add a new story for anchor text, I think we can add it fairly quickly.

**Comment by rlskoeser** [comment]
See #70 for anchor text.
