### ISSUE TITLE
As a user, I want to see the bibliographic details for a single book in Derrida's library so I can see what edition it is and where to get it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#72]
## Notes for testing
This story only includes top-level book information; other book details will be tested separately.

---
As a user, I want to see the bibliographic details for a single book in Derrida's library so I can see what edition it is and where to get it.

- [x] detail view & url
- [x] template for bibliographic detail portion only
- [x] unique, readable slug for url

**Comment by bwhicks** [comment]
Proposed slug from @rlskoeser @bhicks meeting: 

slugified-title-year-identifier-from- #55, 
Truncate on period, colon, comma in title? Distinguish on author?
Editable with 301 edit

Putting this comment on the right story.

**Comment by bwhicks** [comment]
Some initial exploration on this -- year and copy will probably differentiate slug urls sufficiently.

However, we do have an issue with some titles that have unicode chars: Mainly a run of 'oeuvres' that use the `œ` ligature. My instinct is that those need to be standardized to use 'oe'. Otherwise I could see them introducing some odd search results anyway.

While `slugify() has an `allow_unicode=True` flag, that is usually standards breaking without urlencoding the url, which would result in a *really* ugly url.

Piping the detail view via pk for initial testing in any case, but wanted to document the issue.

**Comment by rlskoeser** [comment]
I think this is done except for adding slugs. I'm going to increase the estimate to 2 points to account for that work.

**Comment by araiffe** [comment]
When clicking on the "Bibliography" tab of the books extant in the library, this informations appears accessible.
