### ISSUE TITLE
Library and Book LMS - book cover rollover status 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#77]
- Change rollover status of a book cover to underlining book title (You're not getting the viewer form these pages. The only place should be using this hovering status is the thumbnails in image galley)

![screen shot 2017-07-31 at 2 40 50 pm](https://user-images.githubusercontent.com/17734456/28792822-e29c1fae-75fe-11e7-99b5-2363cd93afb7.png)

<img width="798" alt="screen shot 2017-07-31 at 2 43 45 pm" src="https://user-images.githubusercontent.com/17734456/28792814-ddf8ddb6-75fe-11e7-8904-64ee24919759.png">

**Comment by rlskoeser** [comment]
@kevinglover I don't see the hover status on the main library page.

Also, hover on images in the book detail gallery page seem to be including some padding to the right of the actual image.

**Comment by kevinglover** [comment]
@rlskoeser I thought the only place should be using this hovering status is the thumbnails in image galley?

**Comment by rlskoeser** [comment]
@kevinglover Oh! Yes, I misread Xinyi's comment above.  Sorry about that, I see now.

**Comment by xinyil** [comment]
<img width="1009" alt="screen shot 2017-09-06 at 1 57 11 pm" src="https://user-images.githubusercontent.com/17734456/30126850-4c60e324-930b-11e7-8749-01453d133d4e.png">

- incorrect icon
- color overlay is exceeding the actual image size
- any clue why the animation is so slow?

**Comment by kevinglover** [comment]
@xinyil what would be the correct icon? That's the svg icon specified in the project

**Comment by kevinglover** [comment]
The overlay is limited to the box model and the size related to the image. We can't set both the width and height to be the same as the image because all the images are not guaranteed to be the same dimensions. Currently, we are setting the height and allowing the width to be automatically calculated based on the image source. We could also set the width and the overlay would cover the image completely, but that would risk stretching and distorting the image.

**Comment by kevinglover** [comment]
This is tangentially related to another issues raised with the alignment of the image text.
Since the images are in columns, the width of the containers are fixed, so we are limited to these scenarios: the images are either going to have a set height or will extend 100% width.
This example shows two scenarios: https://codepen.io/kevinglover/pen/KvLoQM

**Comment by xinyil** [comment]
- the icon should be white
- can we treat the images the same way as the book covers? width set to 2 columns, auto height, and can be different

**Comment by kevinglover** [comment]
@xinyil We can do make the images wider and have them set to auto height; that will have the issue where the rollover color might be longer/shorter than the image based on the dimensions of the thumbnail.
