### ISSUE TITLE
Citation card - link behavior 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#85]
- [x] the thumbnail should display the cited page, not the cover
- [x] click on the image will lead you to the viewer (not available now) of this cited page, not the book page
- [x] click on the author will open a filtered library page of that author's books.

<img width="510" alt="screen shot 2017-08-17 at 8 56 33 pm" src="https://user-images.githubusercontent.com/17734456/29439916-0cf33f2e-838f-11e7-916f-037606ed437a.png">

**Comment by rlskoeser** [comment]
Now displays the cited page image when possible.

I think we can make the author filter work (logic is slightly complicated because we display `firstname last` but facet on `lastname, first` and have to handle multiple authors).

@xinyil I'm not sure about linking directly to the image viewer.  That would be the ideal behavior, but for copyright reasons we can't display every page - we're only displaying annotated pages within the book content.  I'm not sure we have enough information in this context to know whether or not we can display the image, and even if we did it would be strange if some images were linked and other weren't.  Any thoughts on what the behavior should be with these constraints?

**Comment by xinyil** [comment]
@rlskoeser Can we know if the page is available dor display by page number?  We could direct people to another error page saying page not available due to copyright restriction, when it's not available. 

If we can't match the information, we could just direct people to image gallery.

**Comment by xinyil** [comment]
@rlskoeser it's fine the link behave differently. we had a diagram clarifying the difference. 

is it possible to have different hover effects? this is the way it was designed on hover:
- if it's no in PUL we'll show the text "not in PUL" 
- if it's going to go to the detail image view, zoom in magnifying glass icon.
- if it's going to **book** page, just the blue overlay

<img width="733" alt="screen shot 2018-03-30 at 11 20 33 am" src="https://user-images.githubusercontent.com/17734456/38143089-fc4466ce-340c-11e8-865f-9e3a93e2b469.png">

**Comment by rlskoeser** [comment]
@xinyil thanks, this is super helpful.  It is possible for us to display the cited page thumbnail for references without corresponding annotations, and that's what the site currently does (where possible).  Restricting to references with corresponding annotations will restrict this _and_ require extra data work from the team; in the data I have there are only 7 References currently associated with corresponding annotations.

I do see the logic in having a different display based on the expected behavior...

What if we can determine whether or not the page viewer can be displayed (i.e. referenced page has annotations, whether or not they correspond to this particular reference)?

**Comment by xinyil** [comment]
@rlskoeser
I think your suggestion is great!
So when a page has annotations, whether or not they correspond to this particular reference, it can be linked to the page viewer, even if the large page image has been suppressed. Then the magnifying glass icon on hover will still make sense.

**Comment by rlskoeser** [comment]
@xinyil small clarification: if a page does not have annotations, can we still display the page thumbnail (maybe with no magnifying glass icon on hover?) or should we display the cover?

**Comment by xinyil** [comment]
@rlskoeser if a page does not have annotations, can we access the large image? if not I think displaying the cover is more logical.

**Comment by kac3** [comment]
@xinyil @rlskoeser This is all sounding very good to me!

**Comment by rlskoeser** [comment]
@xinyil please clarify, for the non-digitized book in the diagram above: are there two placeholder images? We're already using `cover_notinPUL.png` for non digitized content, so I'm unclear what (if anything) needs to be displayed on hover.

**Comment by xinyil** [comment]
@rlskoeser on hover, can we display a blue overlay and the text "Not in PUL". I can mock it up quickly. do you think it'll be easier to use a static image?

**Comment by rlskoeser** [comment]
@xinyil no, let's use text if we can.  That doesn't seem like quite the right wording, though.  "Not digitized" ?

**Comment by kac3** [comment]
@rlskoeser @xinyil Jumping in here to say that there are actually two kinds of books without images: books not extant in the Derrida Library collection (the vast majority) and books that are extant but that we missed in the initial digitization sweep (a few outliers).  Should we distinguish between these?

**Comment by rlskoeser** [comment]
@kac3 thanks - that is what I was concerned about.  I'd prefer wording that covers all known cases for why we might not have a thumbnail (current content and future content if possible).

@kac3 any suggestions for wording?  not available, not digitized?

**Comment by kac3** [comment]
@rlskoeser I think "Not available" is our best bet, then, since it covers all cases. Does that sound good?

**Comment by rlskoeser** [comment]
@kac3 that makes sense to me.

@xinyil I added a hover style to the placeholder, feel free to edit to adjust what you'd like to see in terms of font and size (see commit above for where in the code)

**Comment by rlskoeser** [comment]
@kac3 what Xinyi and I came up with here for thumbnail display and link behavior sounds the ideal, but we don't have time to implement in the current phase.  I did get it updated to work for references with corresponding annotations, and you'll be able to see that soon when we update the test site.  I only see 7 of those in production right now, but presumably there are more.  You can decide when to have the project team to do the data work to have more of these show up in the list.

**Comment by kac3** [comment]
@rlskoeser Sounds good - thanks.  I'll talk to the team about when to begin systematically associating references with annotations (we were waiting to get all of the annotation data in first).

**Comment by rlskoeser** [comment]
@xinyil the updated hover & link behavior based on status is available on the test site

**Comment by xinyil** [comment]
should book cover link to bibliography tab instead of image gallery? which would make more sense?

**Comment by kac3** [comment]
@xinyil I think bibliography tab makes more sense, but curious to know what @rlskoeser thinks.

**Comment by rlskoeser** [comment]
@kac3 @xinyil bibliography tab seems logical, since it's the main landing page for the book - sorry @xinyil, I think I misread your spec or one of your comments and thought you wanted it to link to the gallery.

**Comment by rlskoeser** [comment]
@xinyil @kac3 link behavior is updated on the test site (now goes to bibliography page), if one of you wants to review and sign off.
