### ISSUE TITLE
Book card - link behavior 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#86]
- when rollover the cover thumbnail, the title will turn into it's rollover stage, so people know that it will lead to the book's page when clicking on the cover or title
<img width="260" alt="screen shot 2017-08-17 at 9 00 40 pm" src="https://user-images.githubusercontent.com/17734456/29439967-58c8b690-838f-11e7-8ea4-ceaf48fb71b5.png">

**Comment by xinyil** [comment]
- click on the author will open a filtered library page of that author's books
has not been fixed

**Comment by rlskoeser** [comment]
@xinyil We have a separate issue now for author link - see #89. That functionality requires Solr functionality, which hasn't been implemented yet in this branch.  Please test and accept this one independent of that.

**Comment by xinyil** [comment]
@rlskoeser Thanks for the update!

Also note that titles and images are not aligned.

**Comment by kevinglover** [comment]
We have to be careful with conversions and limit it to 6 decimal places because certain browsers show no difference between 2-5.d.p. Browsers also have different default styles that can affect the calculation of fonts and percentages. In some cases the same percentages will display differently in different browsers. 

We are using ems, as Px have accessibility issues, so I am hesitant to simply use px for everything even though it would be easier to adapt exact measurements. I can use the converter, but just be aware that there could still be some variation on the calculated style.

**Comment by xinyil** [comment]
As far as I understand, browser default to 16px = 1em. 

If someone changed the conversion in browser to a larger px scale, it should be enlarged, and this is exactly why we use ems!

**Comment by rlskoeser** [comment]
@kevinglover is there anything still to be done on this one?  I can't tell from the conversation; the one item previously needed has been handled as a separate issue.
