### ISSUE TITLE
Book - LMS - go back link

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#87]
<img width="1357" alt="screen shot 2017-08-17 at 9 02 56 pm" src="https://user-images.githubusercontent.com/17734456/29440081-10969652-8390-11e7-9a4e-4857ed801b29.png">

**Comment by kevinglover** [comment]
@xinyil What if this is navigated to directly? Where would the back button go in that scenario?

**Comment by rlskoeser** [comment]
Can we make this a breadcrumb rather than a back link?  I don't think the functionality should vary based on how someone got there.

**Comment by xinyil** [comment]
The ideal behavior is that when you go one level back in the breadcrumb, you won't lose active search and filters if you have any.

One live example:
https://www.shopspring.com/lifestyle/home/home_decor/decorative_pillows?priceRangeMax=50&refineFlags=on_sale
<img width="355" alt="screen shot 2017-08-24 at 11 21 13 am" src="https://user-images.githubusercontent.com/17734456/30220966-8df0b794-948f-11e7-8ecb-457244ee6742.png">

**Comment by araiffe** [comment]
I think this works properly but I have one comment -- when you push back, it takes you to the beginning of the list of results, instead of the "page" of results from which you clicked on the link to a book. I.e. Levina's _Difficile liberté_ is on p. 7 of the initial results and if you click on "back" it brings you back to page 1, instead of the page from which you were on when you clicked. I'm not sure if this can be improved.

**Comment by xinyil** [comment]
the go back link is not clickable now.
