### ISSUE TITLE
As a user, I want to see a visualization of references by author of referenced work so that I can get a sense of distribution by cited author.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#93]
## Notes for testing
Update 3/8/2018: please check after reviewing the reference changes in #164 to see that the author is reflected correctly based on the associated book section rather than the collected work.

**Comment by araiffe** [comment]
There is a problem with the visualization related to multi-author works. In particular, the collective work entitled _L'écriture et la psychologie des peuples_ has many authors, each of whom have one or two contributions within this collected work. Each of these authors is given 1 dot in the visualization each time any portion of that work is cited, even though a dot should only appear next to their names when one of their individual works is cited. 

This problem is most bothersome where _L'écriture et la psychologie des peuples_ is concerned, but affects all multi-author works.

Besides this issue, which seems to be a bug, the feature appears to be working properly and is great!

**Comment by rlskoeser** [comment]
I was going to reply on #78 but realized we'd inadvertently put our comments on the wrong ticket.  I don't think you have tested that one yet since you haven't tested #56.  Moving the conversation over here (including our last exchange so we have it all in one place).

Here's my question:
> @araiffe this is helpful - I saw those multi-author works in the lists and wondered about them, but didn't think about the implications for other parts of the site.
>
> Can you provide a couple of examples of book sections within that book for us to work with? When I search on the example you provided I'm only finding the book record.

And your response:
>@rlskoeser Unless I've inadvertently overlooked one, I believe that the sections are as follows:
>
>"La grande invention de l'écriture" by Marcel Cohen,
"Histoire de l'écriture" and "Les sémites et l'alphabet" by James Février,
"Les écritures indiennes" by Jean Filliozat,
"La Chine. Aspects et fonctions de l'écriture" by Jacques Gernet,
"L'écriture cunéiforme et la civilisation mésopotamienne" by René Labat,
"L'Asie mineure. Les Hittites, peuple à double écriture" by Emmanuel Laroche,
"L'écriture et le droit" by Henri Lévy-Bruhl,
"La civilisation égéenne" by Olivier Masson,
"Les Primitifs. Signaux et symboles" by Alfred Métraux.
There are other authors who have chapters in L'écriture et la psychologie des peuples but Derrida doesn't cite their chapters.

I _think_ the system is displaying correctly based on the data as it is in the database.  Here is what I think needs to happen to correct the problem you've identified:
- book chapters should be associated with the larger work via "collected in" so the system knows they are book sections and not books 
- references should be associated with the individual chapters and not the collected work (this is the important one for the visualization)

Is there a smaller collected volume you can test this with?  Don't do all the clean up in the test site, just enough to determine whether or not updating the records as I've suggested corrects the problem.

**Comment by kac3** [comment]
@rlskoeser Ah, I think we were missing the essential piece of associating references with individual sections instead of the entire book. Will fix!

**Comment by araiffe** [comment]
@rlskoeser @kac3 I'm not clear on where in the test site this feature is located to test it… please advise!

**Comment by rlskoeser** [comment]
@araiffe if you click on 'visualization' in the main navigation it's currently the default histogram that's displayed (although we could switch it to make instance of citation the default view if you all prefer).

**Comment by kac3** [comment]
@rlskoeser I was just thinking that I'd like to have instance of citation be the default view! If you could switch it, that would be much appreciated.

**Comment by rlskoeser** [comment]
@kac3 sure, no problem.  Also: are you still happy with "instance of citation" as the label for that view?

**Comment by kac3** [comment]
@rlskoeser It seems like we're moving toward the terminology of "reference" throughout the site, so I'm thinking just "References" might be better.

@araiffe Your thoughts?

**Comment by araiffe** [comment]
@kac3  I agree, "References" seems better to me, too.

**Comment by kac3** [comment]
@rlskoeser Let's go with "References" then!

**Comment by rlskoeser** [comment]
@kac3 @araiffe great, will do!

**Comment by araiffe** [comment]
@xinyil I wonder if it's possible to improve the way the chapter names are displayed in this section by modifying the spacing? 
(i.e. genèse et
structure
de l'Essai
sur
l'origine
des
langues)
![screen shot 2017-10-06 at 13 18 19](https://user-images.githubusercontent.com/26753387/31290057-2736e9ea-aa99-11e7-854e-17708cc51e8d.png)

Also, I think that in Chapter 4 : du supplément à la source : la théorie de l'écriture, we need an unbreakable space before the colon at "… source : la théorie…"= so that it doesn't get separated from the word "source".

**Comment by rlskoeser** [comment]
@kac3 @araiffe we've updated the styles and label; please test again.

**Comment by araiffe** [comment]
@kac3 @rlskoeser I'm reopening this because it seems that when viewed by author of cited work, the problem still persists of having someone like "Raymond Bloch" or "Alphonse Dain" appearing as a dot every time that "L'écriture et la psychologie des peuples" is cited, only because they have a chapter in that book.

**Comment by kac3** [comment]
All authors seem to be reflected correctly now!

**Comment by kac3** [comment]
@rlskoeser Actually, reopening because I realized that a number of authors suspiciously appeared exactly 12 times. It turns out this is the same number of times that all of the authors appear in the reference list (see issue #98).  So, again, possibly a data issue?

**Comment by rlskoeser** [comment]
@kac3 yes, good catch - same issue you identified on #98, please test #164 first so you can figure out what needs to be done for those 12 references.

**Comment by kac3** [comment]
@rlskoeser This did indeed fix the problem, but there's actually another interesting problem here: _L'écriture et la psychologie des peuples_ is a collective work with no single author.  For the sake of testing, I entered the author as the legal copyright holder (the French research body "Centre national de synthèse"), and this might be our best solution.  But I'm realizing we didn't anticipate a situation with a collective author or no author (as you know, the author field is required for every work...).

**Comment by rlskoeser** [comment]
@kac3 of course.  Would it improve matters if we make author optional? 

If you're satisfied that this feature is working, please go ahead and close it.  Let me know if you want to make author optional, and I can make a note on #175 for now.

**Comment by kac3** [comment]
@rlskoeser Great idea -- let's make author optional.

Closing this issue!
